### PR TITLE
Revert back and fix color

### PR DESCRIPTION
**Pull request by m4rc1e**
This PR reverts commit https://github.com/Gue3bara/Cairo/commit/a2d925be0af0599ddc4ec4448609cbbe33796ba3 which had broken the source files. After the revert, I've applied the color that you wanted.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thanks Marc and Gaber!  @Gue3bara, will it be possible to review this next week so that we can work on pushing it into the pipeline? We'd like to begin testing asap.

**Comment by Gue3bara** [comment]
@chrissimpkins I will work on this today and keep you updated 
it shouldn't need time to fix the color codes

**Comment by Gue3bara** [comment]
after merging the reverted version the issue is still present as you can see below 
Screen Shot 2022-07-30 at 1 30 10 PM
@m4rc1e any idea what is causing this ?

**Comment by m4rc1e** [comment]
Looks good to me.

Screenshot 2022-08-01 at 11 48 21


Since we've just merged the PR, have you pulled in the changes using git pull?

**Pull request merged**
